# Generated by Django 4.2.30 on 2026-06-11 16:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0012_attendance_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceAbsenceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_absence_enabled', models.BooleanField(default=True)),
                ('cutoff_time', models.TimeField(default=datetime.time(18, 0))),
                ('notify_internal', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_dashboard', models.BooleanField(default=True)),
                ('payroll_impact_rule', models.CharField(choices=[('justified', 'Absence justifiée'), ('unjustified', 'Absence non justifiée (déduction)'), ('no_impact', 'Sans impact salarial')], default='unjustified', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Paramètres absences automatiques',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='absence_workflow_status',
            field=models.CharField(blank=True, choices=[('pending_validation', 'En attente de validation'), ('confirmed', 'Confirmée'), ('regularized', 'Régularisée'), ('contested', 'Contestée')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='justification_file',
            field=models.FileField(blank=True, null=True, upload_to='absence_justifications/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='justification_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='attendance',
            name='record_source',
            field=models.CharField(choices=[('manual', 'Manuel'), ('auto', 'Automatique')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='responsible_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_auto_absences', to='hr_app.employee'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payslip', 'Nouveau bulletin'), ('leave_approved', 'Congé validé'), ('leave_rejected', 'Congé refusé'), ('leave_pending', 'Demande de congé'), ('absence_alert', 'Alerte absence'), ('absence_auto', 'Absence automatique'), ('evaluation', 'Nouvelle évaluation'), ('training', 'Nouvelle formation'), ('document', 'Nouveau document RH'), ('general', 'Général')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='AbsenceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('regularized', 'Régularisée'), ('auto_created', 'Absence créée')], default='pending', max_length=20)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_alert', to='hr_app.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_alerts', to='hr_app.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_absence_alerts', to='hr_app.employee')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
