# Generated by Django 4.2.30 on 2026-06-11 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_app', '0013_auto_absence_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-start_date', '-id']},
        ),
        migrations.AddField(
            model_name='contract',
            name='annual_leave_days',
            field=models.DecimalField(decimal_places=1, default=25, max_digits=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='assignment_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contract',
            name='benefits_in_kind',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='confidentiality_clause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='contract',
            name='direction_signatory_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='contract',
            name='direction_signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='direction_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='duration_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='employee_obligations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='employee_signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='employee_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='employer_obligations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='hr_signatory_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='contract',
            name='hr_signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='hr_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='indemnities',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='job_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='non_compete_clause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='other_clauses',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='overtime_clause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='parent_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='hr_app.contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='position_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='contract',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='responsibility_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='salary_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='special_clauses',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_SIGNATURE', 'En attente de signature'), ('SIGNED', 'Signé'), ('LOCKED', 'Verrouillé'), ('CANCELLED', 'Annulé'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=30),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='work_schedule',
            field=models.CharField(blank=True, default='08h00 - 17h00', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payslip', 'Nouveau bulletin'), ('leave_approved', 'Congé validé'), ('leave_rejected', 'Congé refusé'), ('leave_pending', 'Demande de congé'), ('absence_alert', 'Alerte absence'), ('absence_auto', 'Absence automatique'), ('contract_expiring', 'Contrat expirant'), ('contract_signed', 'Contrat signé'), ('evaluation', 'Nouvelle évaluation'), ('training', 'Nouvelle formation'), ('document', 'Nouveau document RH'), ('general', 'Général')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='ContractDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(default='pdf', max_length=10)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='hr_app.contract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_number', models.CharField(max_length=50)),
                ('effective_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('salary_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('position_title', models.CharField(blank=True, default='', max_length=150)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('clauses', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_SIGNATURE', 'En attente de signature'), ('SIGNED', 'Signé'), ('LOCKED', 'Verrouillé'), ('CANCELLED', 'Annulé'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=30)),
                ('employee_signed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_signed_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/amendments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='hr_app.contract')),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
                'unique_together': {('contract', 'amendment_number')},
            },
        ),
    ]
