# Generated by Django 4.2.30 on 2026-06-12 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_app', '0014_contracts_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='import_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_imported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manuel'), ('IMPORTED', 'Importé'), ('GENERATED', 'Généré')], default='MANUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='ContractArchiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('IMPORT', 'Importation'), ('EXPORT', 'Exportation'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('ARCHIVE', 'Archivage'), ('VERSION', 'Version')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('file_snapshot', models.FileField(blank=True, null=True, upload_to='contracts/archive/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_logs', to='hr_app.contract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
