# Generated by Django 4.2.30 on 2026-06-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0006_settings_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='cnss_affiliation',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='logo_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='modulefeature',
            name='feature_type',
            field=models.CharField(choices=[('menu_tab', 'Onglet / Menu'), ('payroll_gain', 'Gain de paie'), ('payroll_retention', 'Retenue de paie'), ('recruitment_step', 'Étape recrutement'), ('training_type', 'Type formation'), ('portal_section', 'Section portail'), ('leave_type', 'Type de congé'), ('kpi_indicator', 'Indicateur KPI'), ('evaluation_method', "Méthode d'évaluation"), ('report_widget', 'Widget reporting'), ('general', 'Fonctionnalité générale')], default='general', max_length=30),
        ),
    ]
