# Generated by Django 4.2.30 on 2026-06-09 09:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0010_recruitment_module_enhanced'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Catégories de compétences',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='performancereview',
            options={'ordering': ['-review_date']},
        ),
        migrations.AddField(
            model_name='performancereview',
            name='comments_future_goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='comments_improvement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='comments_recommendations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='comments_strengths',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='comments_weaknesses',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_reviews', to='hr_app.department'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='evaluation_period',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='result',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='star_rating',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='training',
            name='instructor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='training',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='training',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Organisme de formation'),
        ),
        migrations.AddField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('Planned', 'Planifiée'), ('InProgress', 'En cours'), ('Completed', 'Terminée'), ('Cancelled', 'Annulée')], default='Planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('Stage', 'Stage'), ('Consultant', 'Consultant'), ('Freelance', 'Freelance'), ('Intérim', 'Intérim')], max_length=20),
        ),
        migrations.AlterField(
            model_name='training',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='trainings', to='hr_app.employee'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('required_level', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('expert', 'Expert')], default='intermediaire', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hr_app.skillcategory')),
            ],
            options={
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('target_date', models.DateField()),
                ('priority', models.CharField(choices=[('Low', 'Basse'), ('Medium', 'Moyenne'), ('High', 'Haute')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('NotStarted', 'Non commencé'), ('InProgress', 'En cours'), ('Completed', 'Réalisé'), ('Late', 'En retard')], default='NotStarted', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='hr_app.employee')),
            ],
            options={
                'ordering': ['-target_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit', models.CharField(choices=[('FC', 'FC'), ('USD', 'USD ($)'), ('PERCENT', '%'), ('SALES', 'Ventes'), ('CLIENTS', 'Clients'), ('HOURS', 'Heures'), ('DAYS', 'Jours'), ('FILES', 'Dossiers'), ('PROJECTS', 'Projets')], default='PERCENT', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='hr_app.employee')),
            ],
            options={
                'verbose_name': 'KPI employé',
                'verbose_name_plural': 'KPI employés',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(blank=True, default='', max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_number', models.CharField(blank=True, default='', max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='hr_app.employee')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('expert', 'Expert')], default='debutant', max_length=20)),
                ('acquired_date', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='hr_app.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='hr_app.skill')),
            ],
            options={
                'ordering': ['-acquired_date'],
                'unique_together': {('employee', 'skill')},
            },
        ),
    ]
